Enable authn and authz in Fedora
fcrepo4-labs/fcrepo-api-x-demo pull request #58
Opened 2017-09-18 01:25 UTC by birkland

- Use fcrepo-webapp-plus instead of stock fedora, as it has webac built in
- Configure Fedora (tomcat) for authn
- Configure apix, camel, and extensions to use authn
- Update exercises in guide to add username/password when required
- Use shell script to bootstrap Amherst examples, rather than self-loading

2017-09-18 14:15 UTC, emetsger requested changes

2017-09-18 14:15 UTC, emetsger commented on .env
> +PUBLIC_REPOSITORY_HOST=localhost
Documentation on this variable and how it relates to APIX_PORT and APIX_BASEURI?  It isn't clear to me how this variable is used.

2017-09-18 14:16 UTC, emetsger commented on .env
> +PUBLIC_REPOSITORY_HOST=localhost
Indexing doesn't seem to be working, even with a correct `.env` file for `docker-machine` and fresh images:

esm:~/workspaces/apix/fcrepo-api-x-demo (pr-58)*$ docker images
REPOSITORY                    TAG                 IMAGE ID            CREATED             SIZE
fcrepoapix/apix-fits          1.1.1               68e80970c5e0        7 minutes ago       303.7 MB
fcrepoapix/apix-acrepo        1.1.0-1             59897ea138fa        8 minutes ago       237.6 MB
fcrepoapix/apix-indexing      0.3.0-SNAPSHOT-1    91e34327f78c        9 minutes ago       172.3 MB
fcrepoapix/apix-rdfvis        1.0.0-1             5098c2051a61        10 minutes ago      97.11 MB
fcrepoapix/apix-core          0.3.0-SNAPSHOT-1    33b29e51ee93        11 minutes ago      173.1 MB
fcrepoapix/apix-fcrepo        4.7.4-1             5bad5daf043e        12 minutes ago      172 MB
fcrepoapix/apix-fuseki        3.4.0               b8419dd0db6e        13 minutes ago      143.6 MB
fcrepoapix/apix-karaf-camel   <none>              b97724ffc83c        2 weeks ago         153.4 MB
tomcat                        <none>              4560891aa934        6 weeks ago         113 MB
fcrepoapix/apix-karaf-camel   <none>              6864d3d4e764        3 months ago        154.8 MB
tomcat                        <none>              877ea9315a49        3 months ago        111.3 MB
alpine                        <none>              02674b9cb179        4 months ago        3.987 MB
esm:~/workspaces/apix/fcrepo-api-x-demo (pr-58)*$ cat .env 
PUBLIC_REPOSITORY_HOST=192.168.99.100

# This is the *public facing* API-X port and baseURI.  If changing the default, you need to edit the next two lines
APIX_PORT=80
APIX_BASEURI=http://192.168.99.100/fcrepo/rest

# If changing the fedora host, port, or context path, you need to update all
# the FCREPO_* variables with the updated value!
FCREPO_HOST=fcrepo
FCREPO_PORT=8080
FCREPO_CONTEXT_PATH=/fcrepo
FCREPO_BASEURI=http://fcrepo:8080/fcrepo/rest
FCREPO_PROXYURI=http://fcrepo:8080/fcrepo

CAMEL_FCREPO_AUTHUSERNAME=fedoraAdmin
CAMEL_FCREPO_AUTHPASSWORD=secret3

APIX_LOADER_PORT=8081
FUSEKI_PORT=3030
FITS_PORT=8082

ACREPO_FITS_PORT=9106
ACREPO_IMAGE_PORT=9105
ACREPO_ORE_PORT=9108
ACREPO_PCDM_PORT=9107
ACREPO_SERIALIZE_XML_PORT=9104

EXT_RDF_VIS_PORT=12000

> 2017-09-18 14:11:31,909 | WARN  | Consumer[fedora] | EndpointMessageListener          | 55 - org.apache.camel.camel-core - 2.19.2 | Execution of JMS message listener failed. Caused by: [org.apache.camel.RuntimeCamelException - java.lang.IllegalArgumentException: Credentials may not be null]
org.apache.camel.RuntimeCamelException: java.lang.IllegalArgumentException: Credentials may not be null
	at org.apache.camel.util.ObjectHelper.wrapRuntimeCamelException(ObjectHelper.java:1774)[55:org.apache.camel.camel-core:2.19.2]
	at org.apache.camel.component.jms.EndpointMessageListener$EndpointMessageListenerAsyncCallback.done(EndpointMessageListener.java:195)[56:org.apache.camel.camel-jms:2.19.2]
	at org.apache.camel.component.jms.EndpointMessageListener.onMessage(EndpointMessageListener.java:116)[56:org.apache.camel.camel-jms:2.19.2]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:721)[73:org.apache.servicemix.bundles.spring-jms:4.3.5.RELEASE_1]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:681)[73:org.apache.servicemix.bundles.spring-jms:4.3.5.RELEASE_1]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)[73:org.apache.servicemix.bundles.spring-jms:4.3.5.RELEASE_1]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:317)[73:org.apache.servicemix.bundles.spring-jms:4.3.5.RELEASE_1]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:255)[73:org.apache.servicemix.bundles.spring-jms:4.3.5.RELEASE_1]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1166)[73:org.apache.servicemix.bundles.spring-jms:4.3.5.RELEASE_1]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1158)[73:org.apache.servicemix.bundles.spring-jms:4.3.5.RELEASE_1]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1055)[73:org.apache.servicemix.bundles.spring-jms:4.3.5.RELEASE_1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748)[:1.8.0_131]
Caused by: java.lang.IllegalArgumentException: Credentials may not be null
	at org.apache.http.util.Args.notNull(Args.java:54)[82:org.apache.httpcomponents.httpcore:4.4.5]
	at org.apache.http.auth.AuthState.update(AuthState.java:113)[81:org.apache.httpcomponents.httpclient:4.5.2]
	at org.fcrepo.client.FcrepoHttpClientBuilder$PreemptiveAuthInterceptor.process(FcrepoHttpClientBuilder.java:119)[149:org.fcrepo.client.fcrepo-java-client:0.3.0]
	at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:133)[82:org.apache.httpcomponents.httpcore:4.4.5]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:182)[81:org.apache.httpcomponents.httpclient:4.5.2]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)[81:org.apache.httpcomponents.httpclient:4.5.2]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)[81:org.apache.httpcomponents.httpclient:4.5.2]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)[81:org.apache.httpcomponents.httpclient:4.5.2]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)[81:org.apache.httpcomponents.httpclient:4.5.2]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)[81:org.apache.httpcomponents.httpclient:4.5.2]
	at org.fcrepo.client.FcrepoClient.executeRequest(FcrepoClient.java:216)[149:org.fcrepo.client.fcrepo-java-client:0.3.0]
	at org.fcrepo.client.FcrepoClient.executeRequest(FcrepoClient.java:205)[149:org.fcrepo.client.fcrepo-java-client:0.3.0]
	at org.fcrepo.client.RequestBuilder.perform(RequestBuilder.java:78)[149:org.fcrepo.client.fcrepo-java-client:0.3.0]
	at org.fcrepo.camel.FcrepoProducer.getMetadataUri(FcrepoProducer.java:251)[144:org.fcrepo.camel.fcrepo-camel:4.5.0]
	at org.fcrepo.camel.FcrepoProducer.getUri(FcrepoProducer.java:225)[144:org.fcrepo.camel.fcrepo-camel:4.5.0]
	at org.fcrepo.camel.FcrepoProducer.doRequest(FcrepoProducer.java:194)[144:org.fcrepo.camel.fcrepo-camel:4.5.0]
	at org.fcrepo.camel.FcrepoProducer.process(FcrepoProducer.java:156)[144:org.fcrepo.camel.fcrepo-camel:4.5.0]
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61)[55:org.apache.camel.camel-core:2.19.2]
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:145)[55:org.apache.camel.camel-core:2.19.2]
	at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77)[55:org.apache.camel.camel-core:2.19.2]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:541)[55:org.apache.camel.camel-core:2.19.2]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:198)[55:org.apache.camel.camel-core:2.19.2]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:120)[55:org.apache.camel.camel-core:2.19.2]
	at org.apache.camel.processor.Pipeli [...]

2017-09-18 14:20 UTC, emetsger commented on .env
> +PUBLIC_REPOSITORY_HOST=localhost
RdfVis extension seems to error out as well:

```
esm:~/workspaces/apix/fcrepo-api-x-demo (pr-58)*$ curl -I http://192.168.99.100/services/demo:rdfvis/text
HTTP/1.1 500 Server Error
Content-Type: text/html; charset=UTF-8
Accept: */*
Apix-Exposed-Uri: http://192.168.99.100/services/demo:rdfvis/
Apix-Ldp-Resource: http://fcrepo:8080/fcrepo/rest
Apix-Ldp-Resource-Path: /
Apix-Resource: http://192.168.99.100/fcrepo/rest/
breadcrumbId: ID-5729857b1be4-39328-1505743631413-0-427
X-Powered-By: PHP/7.0.21
Content-Length: 0
Server: Jetty(9.2.19.v20160908)

esm:~/workspaces/apix/fcrepo-api-x-demo (pr-58)*$ curl -I -u fedoraAdmin:secret3 http://192.168.99.100/services/demo:rdfvis/text
HTTP/1.1 500 Server Error
Content-Type: text/html; charset=UTF-8
Accept: */*
Apix-Exposed-Uri: http://192.168.99.100/services/demo:rdfvis/
Apix-Ldp-Resource: http://fcrepo:8080/fcrepo/rest
Apix-Ldp-Resource-Path: /
Apix-Resource: http://192.168.99.100/fcrepo/rest/
Authorization: Basic ZmVkb3JhQWRtaW46c2VjcmV0Mw==
breadcrumbId: ID-5729857b1be4-39328-1505743631413-0-433
X-Powered-By: PHP/7.0.21
Content-Length: 0
Server: Jetty(9.2.19.v20160908)

esm:~/workspaces/apix/fcrepo-api-x-demo (pr-58)*$ 
```

With log messages like:

```
[Mon Sep 18 14:19:14 2017] 172.19.0.5:43156 [500]: /rdfVis/text - Uncaught Error: Class 'EasyRdf_Http_Exception' not found in /www/lib/EasyRdf/Graph.php:325
Stack trace:
#0 /www/index.php(25): EasyRdf_Graph->load()
#1 {main}
  thrown in /www/lib/EasyRdf/Graph.php on line 325
```

2017-09-18 14:21 UTC, emetsger commented on .env
> +PUBLIC_REPOSITORY_HOST=localhost
Seems like something is broken, and I'm wondering if it is because I'm working in `docker-machine`?

2017-09-19 13:52 UTC, emetsger commented
The service document index works, but the repo triple index shows up empty in my browser, with this in the logs:
```
- 2.19.2 | Failed delivery for (MessageId: ID:49238c4691fc-33860-1505828744450-4:1:1:1:19 on ExchangeId: ID-5200b4825d4d-44859-1505828676477-0-19). Exhausted after delivery attempt: 11 caught: java.lang.IllegalArgumentException: Credentials may not be null. Processed by failure processor: FatalFallbackErrorHandler[Channel[Log(FcrepoTriplestoreUpdater)[Index Routing Error: ${routeId}]]]

Message History
---------------------------------------------------------------------------------------------------------------------------------------
RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
[FcrepoTriplestoreR] [FcrepoTriplestoreR] [broker://topic:fedora                                                         ] [     10167]
[FcrepoTriplestoreR] [process1          ] [Processor@0x4d6dc92f                                                          ] [         2]
[FcrepoTriplestoreR] [choice1           ] [when[{(header{header(CamelFcrepoEventType)} contains http://fedora.info/defini] [     10141]
[FcrepoTriplestoreR] [to2               ] [direct:index.triplestore                                                      ] [     10141]
[FcrepoTriplestoreI] [filter1           ] [filter[{not (in ([(header{header(CamelFcrepoUri)} startsWith constant{http://l] [     10141]
[FcrepoTriplestoreI] [removeHeaders1    ] [removeHeaders[CamelHttp*]                                                     ] [         0]
[FcrepoTriplestoreI] [choice2           ] [when[simple{Simple: {{indexing.predicate}} != 'true'}]choice[]                ] [     10139]
[FcrepoTriplestoreI] [to4               ] [direct:update.triplestore                                                     ] [     10139]
[FcrepoTriplestoreU] [setHeader1        ] [setHeader[CamelFcrepoNamedGraph]                                              ] [         0]
[FcrepoTriplestoreU] [to9               ] [fcrepo:{{fcrepo.baseUrl}}?accept=application/n-triples&preferOmit={{prefer.omi] [     10138]
[FcrepoTriplestoreU] [log1              ] [log                                                                           ] [         1]

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------
java.lang.IllegalArgumentException: Credentials may not be null
	at org.apache.http.util.Args.notNull(Args.java:54)[82:org.apache.httpcomponents.httpcore:4.4.5]
	at org.apache.http.auth.AuthState.update(AuthState.java:113)[81:org.apache.httpcomponents.httpclient:4.5.2]
	at org.fcrepo.client.FcrepoHttpClientBuilder$PreemptiveAuthInterceptor.process(FcrepoHttpClientBuilder.java:119)[149:org.fcrepo.client.fcrepo-java-client:0.3.0]
	at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:133)[82:org.apache.httpcomponents.httpcore:4.4.5]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:182)[81:org.apache.httpcomponents.httpclient:4.5.2]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)[81:org.apache.httpcomponents.httpclient:4.5.2]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)[81:org.apache.httpcomponents.httpclient:4.5.2]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)[81:org.apache.httpcomponents.httpclient:4.5.2]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)[81:org.apache.httpcomponents.httpclient:4.5.2]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)[81:org.apache.httpcomponents.httpclient:4.5.2]
	at org.fcrepo.client.FcrepoClient.executeRequest(FcrepoClient.java:216)[149:org.fcrepo.client.fcrepo-java-client:0.3.0]
	at org.fcrepo.client.FcrepoClient.executeRequest(FcrepoClient.java:205)[149:org.fcrepo.client.fcrepo-java-client:0.3.0]
	at org.fcrepo.client.RequestBuilder.perform(RequestBuilder.java:78)[149:org.fcrepo.client.fcrepo-java-client:0.3.0]
	at org.fcrepo.camel.FcrepoProducer.getMetadataUri(FcrepoProducer.java:251)[144:org.fcrepo.camel.fcrepo-camel:4.5.0]
	at org.fcrepo.camel.FcrepoProducer.getUri(FcrepoProducer.java:225)[144:org.fcrepo.camel.fcrepo-camel:4.5.0]
	at org.fcrepo.camel.FcrepoProducer.doRequest(FcrepoProducer.java:194)[144:org.fcrepo.camel.fcrepo-camel:4.5.0]
	at org.fcrepo.camel.FcrepoProducer.process(FcrepoProducer.java:156)[144:org.fcrepo.camel.fcrepo-camel:4.5.0]
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61)[55:org.apache.camel.camel-core:2.19.2]
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:145)[55:org.apache.camel.camel-core:2.19.2]
	at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77)[55:org.apache.camel.camel-core:2.19.2]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:541)[55:org.apache.camel.camel-core:2.19.2]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:198)[55:org.apache.camel.camel-core:2.19.2]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:120)[55:org.apache.camel.camel-core:2.19.2]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:83)[55:org.apache.camel.camel-core:2.19.2]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:198)[55:org.apache.camel.camel-core:2.19.2]
	at org.apache.camel.component.direct.DirectProducer.process(DirectProducer.java:62)[55:org.apache.camel.camel-core:2.19.2]
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:145)[55:org.apache.camel.camel-core:2.19.2]
	at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77)[55:org.apache.camel.camel-core:2.19.2]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:541)[55:org.apache.camel.camel-core:2.19.2]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:198)[55:org.apache.camel.camel-core:2.19.2]
	at org.apache.camel.processor.ChoiceProcessor.process(ChoiceProcessor.java:117)[55:org.apache.camel.camel-core:2.19.2]
	at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77)[55:org.apache.camel.camel-core:2.19.2]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:541)[55:org.apache.camel.camel-core:2.19.2]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:198)[55:org.apache.camel.camel-core:2.19.2]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:120)[55:org.apache.camel.camel-core:2.19.2]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:83)[55:org.apache.camel.camel-core:2.19.2]
	at org.apache.camel.processor.FilterProcessor.process(FilterProcessor.java:57)[55:org.apache.camel.camel-core:2.19.2]
	at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77)[55:org.apache.camel.camel-core:2.19.2]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:541)[55:org.apache.camel.camel-core:2.19.2]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:198)[55:org.apache.camel.camel-core:2.19.2]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:198)[55:org.apache.camel.camel-core:2.19.2]
	at org.apache.camel.component.direct.DirectProducer.process(DirectProducer.java:62)[55:org.apache.camel.camel-core:2.19.2]
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:145)[55:org.apache.camel.camel-core:2.19.2]
	at org.apache.camel.management.InstrumentationProcessor.process(Instrumentation [...]

2017-09-19 13:57 UTC, emetsger commented
Service documents can be retrieved without authentication.  Not sure if that is by design or not:

```
esm:~/workspaces/apix/fcrepo-api-x-demo (pr-58)*$ curl http://192.168.99.100/discovery/images/
<>      a       <http://fedora.info/definitions/v4/service#ServiceDocument> ;
        <http://fedora.info/definitions/v4/service#isServiceDocumentFor>
                <http://192.168.99.100/fcrepo/rest/images> ;
        <http://www.openarchives.org/ore/terms/describes>
                <#services> .

<#0e093583-3c3f-4d24-ba3b-c77b112a592d>
        a       <http://fedora.info/definitions/v4/service#ServiceInstance> ;
        <http://fedora.info/definitions/v4/service#hasEndpoint>
                <http://192.168.99.100/services/images/demo:rdfvis/> ;
        <http://fedora.info/definitions/v4/service#isFunctionOf>
                <http://192.168.99.100/fcrepo/rest/images> ;
        <http://fedora.info/definitions/v4/service#isServiceInstanceOf>
                <http://example.org/services/RdfVisualization> ;
        <http://fedora.info/definitions/v4/service#serviceInstanceExposedBy>
                <http://192.168.99.100/fcrepo/rest/images> .

<#6c9b9ef3-df0f-438e-ac42-ab4c4651c9a4>
        a       <http://fedora.info/definitions/v4/service#ServiceInstance> ;
        <http://fedora.info/definitions/v4/service#hasEndpoint>
                <http://192.168.99.100/services/images/svc:ore> ;
        <http://fedora.info/definitions/v4/service#isFunctionOf>
                <http://192.168.99.100/fcrepo/rest/images> ;
        <http://fedora.info/definitions/v4/service#isServiceInstanceOf>
                <http://acdc.amherst.edu/ns/registry#OreService> ;
        <http://fedora.info/definitions/v4/service#serviceInstanceExposedBy>
                <http://192.168.99.100/fcrepo/rest/images> .

<#services>  <http://www.openarchives.org/ore/terms/aggregates>
                <#6c9b9ef3-df0f-438e-ac42-ab4c4651c9a4> , <#0e093583-3c3f-4d24-ba3b-c77b112a592d> .
esm:~/workspaces/apix/fcrepo-api-x-demo (pr-58)*$ 
```

2017-09-19 14:01 UTC, emetsger commented
Accessing the rdfvis service _without_ providing credentials returns a `401` but no `WWW-Authenticate` header, so it can be unclear, and maybe not possible, when interacting the service in a browser to add authentication credentials with the request.

2017-09-19 14:13 UTC, emetsger commented
It seems the ORE service isn't working, but I'm not sure if that is due to authentication issues or not:
```
sm:~/workspaces/apix/fcrepo-api-x-demo (pr-58)*$ curl --verbose http://192.168.99.100/services/images/svc:ore
*   Trying 192.168.99.100...
* Connected to 192.168.99.100 (192.168.99.100) port 80 (#0)
> GET /services/images/svc:ore HTTP/1.1
> Host: 192.168.99.100
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Accept: */*
< Accept-Encoding: gzip,deflate
< Apix-Exposed-Uri: http://192.168.99.100/services/images/svc:ore
< Apix-Ldp-Resource: http://fcrepo:8080/fcrepo/rest/images
< Apix-Ldp-Resource-Path: /images
< Apix-Resource: http://192.168.99.100/fcrepo/rest/images
< breadcrumbId: ID-3bd8f4e736cb-44312-1505828678682-0-541
< Content-Length: 0
< Server: Jetty(9.2.19.v20160908)
< 
* Connection #0 to host 192.168.99.100 left intact
esm:~/workspaces/apix/fcrepo-api-x-demo (pr-58)*$ curl --verbose -u fedoraAdmin:secret3 http://192.168.99.100/services/images/svc:ore
*   Trying 192.168.99.100...
* Connected to 192.168.99.100 (192.168.99.100) port 80 (#0)
* Server auth using Basic with user 'fedoraAdmin'
> GET /services/images/svc:ore HTTP/1.1
> Host: 192.168.99.100
> Authorization: Basic ZmVkb3JhQWRtaW46c2VjcmV0Mw==
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Accept: */*
< Accept-Encoding: gzip,deflate
< Apix-Exposed-Uri: http://192.168.99.100/services/images/svc:ore
< Apix-Ldp-Resource: http://fcrepo:8080/fcrepo/rest/images
< Apix-Ldp-Resource-Path: /images
< Apix-Resource: http://192.168.99.100/fcrepo/rest/images
< Authorization: Basic ZmVkb3JhQWRtaW46c2VjcmV0Mw==
< breadcrumbId: ID-3bd8f4e736cb-44312-1505828678682-0-544
< Content-Length: 0
< Server: Jetty(9.2.19.v20160908)
< 
* Connection #0 to host 192.168.99.100 left intact
esm:~/workspaces/apix/fcrepo-api-x-demo (pr-58)*$ 
```

2017-09-22 16:34 UTC, birkland commented on .env
> +PUBLIC_REPOSITORY_HOST=localhost
rdfvis, documentation of `PUBLIC_REPOSITORY_URI` fixed

2017-09-22 16:35 UTC, birkland commented
Service document auth is by design - it doesn't necessarily have to access the repository to generate it.  If it's desired to be protected, then the admin would need to secure its endpoints in much the same manner as they secure Fedora.

2017-09-22 16:36 UTC, birkland commented
Fixed indexing, I think.  The problem was that host was always defaulting to `localhost`

2017-09-22 16:50 UTC, birkland commented
The ORE service appears to do _nothing_ regardless of auth.  This PR makes no difference

2017-09-22 19:54 UTC, merged